version: '3.4'

services:
  shardingapi:
    image: ${DOCKER_REGISTRY-}shardingapi
    build:
      context: .
      dockerfile: ShardingAPI\Dockerfile

  azuresearchdemo:
    image: ${DOCKER_REGISTRY-}azuresearchdemo
    build:
      context: .
      dockerfile: AzureSearchDemo\Dockerfile

