version: '3.4'

services:
  shardingapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- Services__Products=http://nameofotherapi_as_shardingapi_inaboveexample
      #The above needs to be added in the docker-compose.override.yml if our main api is calling other APIs
    ports:
      - "1234:80"

  azuresearchdemo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4567:80"

